name: Deploy to Server

on:
  push:
    branches:
      - main  # Ejecutar cuando haya cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Usar la clave privada almacenada como secreto

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@your-server-ip << 'EOF'
        cd /var/www/html
        git pull origin main
        docker-compose down
        docker-compose up -d --build
        EOF

